# agent runtime: gateway + tenant overlay + agent Brain seed.
# default/start = full boot (entrypoint seeds config + workspace, then runs gateway).
version: '3'

vars:
  DEV_ENV: "OPENCLAW_ENTRY=../openclaw/openclaw.mjs OPENCLAW_BUNDLED_PLUGINS_DIR=../openclaw/extensions OPENCLAW_CUSTOM_PLUGINS_DIR=./extensions"

tasks:
  default:
    desc: Run gateway locally (runtime + pack seed, dev env)
    cmds:
      - "{{.DEV_ENV}} ./scripts/entrypoint.sh"

  local:
    desc: Alias for default (run gateway locally)
    cmds:
      - task: default

  upgrade-openclaw:
    desc: Clone/update and build openclaw runtime (scripts/upgrade-openclaw.sh)
    cmds:
      - ./scripts/upgrade-openclaw.sh

  start:
    desc: Run gateway (runtime + pack seed, production-like)
    cmds:
      - ./scripts/entrypoint.sh

  skill-setup:
    desc: Run skill-setup scripts only (agent Brain skills)
    cmds:
      - ./scripts/skill-setup.sh

  config:apply:
    desc: Apply .env to openclaw.json (tenant overlay template → state dir)
    cmds:
      - ./scripts/apply-env-to-config.sh
