platform_toolsets:
  cli: [web, terminal, file, vision, image_gen, browser, skills, todo, memory, session_search, clarify, code_execution, cronjob]
toolsets:
  - web
  - terminal
  - file
  - vision
  - image_gen
  - browser
  - skills
  - todo
  - memory
  - session_search
  - clarify
  - code_execution
  - cronjob
